config/routes.rb
Rails.application.routes.draw do

  get 'votes/new'

  get 'votes/create'
 
devise_for :users
root to: "questions#index"
 get 'questions/upvote'
 get 'questions/downvote'
 get 'answers/upvote'
 get 'answers/downvote'
resources :questions do
  resources :answers do
    resources :votes
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :question_tags, dependent: :destroy
  has_many :tags , through: :question_tags , dependent: :destroy
  acts_as_votable

  # def self.search(search)
  #   if search
  #     where('title LIKE ?', "%#{search}%")
  #   else
  #     []
  #   end
  # end

  def self.search(search, page)
    if search
      where('title LIKE ?', "%#{search}%").paginate(page:page, per_page:2)
    else
      paginate(page:page, per_page:2)
    end
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:authenticate_user!,:show, :edit, :update, :destroy,:upvote,:downvote]
  before_action :authenticate_user!, only: [:new,:create]
 

  # GET /questions
  # GET /questions.json
  def index
    @questions_all = Question.all
    @questions = @questions_all.sort_by{|question| question.weighted_score}.reverse
    @lastQuestions = Question.all.reverse
    @tags = Tag.all
    @findQuestions = Question.search(params[:search],params[:page])
    @findQuestion = @findQuestions.sort_by{|question| question.weighted_score}.reverse
    @tagQuestions = Tag.find_by(name:"#{params[:search]}".capitalize)
    respond_to do |format|
      format.html { render :index }
      format.json { render jsonapi: @questions}
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @relatedQuestions = @question.tags.inject([]){|pote,tag| pote.push(*tag.questions)}.uniq.shuffle
    @relatedQuestions  = @relatedQuestions.select{|qr| qr.id != @question.id}
    @answers = @question.answers.where(status:"accepted") + @question.answers.reject {|a| a.status == "accepted"}.sort_by{|answer| answer.weighted_score}.reverse
    @answer = Answer.new
    # @tags = question.tags
    @vote = Vote.find_by({votable_type: "Question",votable_id: @question.id,voter_id:current_user.id}) if(current_user)
    if(@vote)
      if(@vote.vote_flag)
        @td_class = 'far'
        @tu_class = 'fas'
      else 
        @td_class = 'fas'
        @tu_class = 'far'
      end
    else
    
      @td_class = 'far'
      @tu_class = 'far'
    end
    @question_votes = Vote.where({votable_type: :Question, votable_id:@question.id})
    @question_votes = @question_votes.select{|vote| vote.vote_flag}.size - @question_votes.select{|vote| !vote.vote_flag}.size
    respond_to do |format|
      format.html { render :show }
      format.json { render jsonapi: @question}
  
  end

end
  # GET /questions/new
  def new
    # @tags = Tag.all
    @questiontag = QuestionTag.new
    @question = Question.new
    @tags = []
    # render :layout => 'special_layout'
  end

  # GET /questions/1/edit
  def edit
    
    @questiontag = QuestionTag.where(question_id:@question.id)
    @tags = @questiontag.map{|qt| qt.tag_id}
    
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params.merge!({user_id:current_user.id}))
    
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
         params[:question][:question_tag][:tag_id].each do |id| 
          if id.present?
            @questiontag = QuestionTag.create(question_id:@question.id, tag_id:id)
          end
        end
        puts params
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
   
  end
  

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      @question.question_tags.map{|qt| qt.destroy}
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
        params[:question][:question_tag][:tag_id].each do |id| 
          if id.present?
            @questiontag = QuestionTag.create(question_id:@question.id, tag_id:id)
          end
        end
        puts params
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
    @vote=Vote.find_by({votable_type:"Question",votable_id:@question.id,voter_id:current_user.id}) if current_user
    if !@vote  && current_user
      current_user.likes @question
    elsif(@vote)
      if(@vote.vote_flag)
        @vote.destroy
      else
        @vote.update(vote_flag: true)
      end
    end
    
    redirect_to question_path(@question)
  end

  def downvote
      @vote=Vote.find_by({votable_type:"Question",votable_id:@question.id,voter_id:current_user.id}) if current_user
      if !@vote  && current_user
        current_user.dislikes @question
      elsif(@vote)
        if(!@vote.vote_flag)
          @vote.destroy
        else
          @vote.update(vote_flag:false)
        end
      end 
       
      redirect_to question_path(@question)
end 
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :body, tag_id: [])
    end
 
   
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :título, class: 'font-weight-bold'
    = f.text_field :title, :required => true, placeholder:"¿Cuál es tu pregunta? Sé específico", id: "title", class: 'form-control'
  .field.mt-4
    = f.label :redacta_tu_pregunta_aquí, class: 'font-weight-bold'
    = f.trix_editor :body, :required => true, rows: "10",id: 'body', class: 'form-control ', "trix-change":"a"
    %button.btn.btn-outline-secondary.btn-sm{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"} html preview
  .field.mt-4
    = f.label :etiquetas, class: 'font-weight-bold'
    .tagss
      = f.fields_for @questiontag do |qt|
        = qt.collection_select :tag_id, Tag.all, :id, :name, {:selected => @tags }, {multiple: true, class:"form-control tagss"}
    = f.submit 'Publicar tu pregunta', class:'btn btn-outline-primary mt-4 mb-4 '
    .container
      / Trigger the modal with a button
      / Modal
      #myModal.modal.fade{:role => "dialog"}
        .modal-dialog.modal-lg
          .modal-content
            .modal-header
              %h4.modal-title Escriba su codigo html y css::
            .modal-body          
              .main
                .header
                .menu
                .content
                .row
                  .col-6
                    %textarea#editor
                      :preserve
                  .col-6
                    %iframe#browser
            .modal-footer
              %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
              .row
                .col-12.text-right
                  %input{:onclick => "myTRY()", :type => "button",:id => "envivo", :value => "RUN", :class => "btn btn-outline-secondary border-radius:10px"}/
   

app/views/questions/_formanswer.html.haml
= form_for [@question, @answer] do |f|
	- if @answer.errors.any?
		#error_explanation
			%h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
			%ul
				- @answer.errors.full_messages.each do |message|
					%li= message
	.field.border-bottom.pb-5 
		= f.trix_editor :body, rows:"50", class: 'form-control '
	.actions.mt-4.text-center
		= f.submit 'Publicar respuesta',class:'btn btn-outline-primary'

app/views/questions/edit.html.haml
.container.mt-5
    = render "form"


    = link_to 'Show', @question
    \|
    = link_to 'Back', questions_path

app/views/questions/index.html.haml
.container
  -if @tagQuestions != nil && @tagQuestions.questions != []
    .row.mt-3.justify-content-center
      .col-5.categorys
        %ul.nav.nav-tabs.border-bottom-0.mt-5{:role => "tablist"}
          %li.nav-item.w-100.text-center
            %a.nav-link.active.border-left-0.font-weight-bold{"data-toggle" => "tab", :href => "#home"} Resultados de la busqueda
      .col-4.text-right.mt-2
        = link_to new_question_path do
          %button.btn.btn-primary.mt-0.p-2.rounded-0{:type => "button"}
            Formular pregunta
    .row.justify-content-center
      .col-9
        .tab-content          
          %table.table#popularquestions.bg-white
            %tbody
              -@taggy = @tagQuestions.questions.paginate(page: params[:page], per_page: 5)
              - @taggy.each do |question|
                -@question_votes = Vote.where({votable_type: :Question, votable_id:question.id})
                -@question_votes = @question_votes.select{|vote| vote.vote_flag}.size - @question_votes.select{|vote| !vote.vote_flag}.size
                %tr.border-top-0
                  -if @question_votes  < 0
                    %td.align-middle.text-center.pb-0
                      %h6.d-inline-block.text-danger.mr-3.p-2.border.border-danger
                        = @question_votes
                        .small
                          votos
                      %h6.d-inline-block.text-secondary.ml-3
                        = question.answers.length
                        .small
                          respuestas
                  -elsif @question_votes  > 0
                    %td.align-middle.text-center.pb-0
                      %h6.d-inline-block.text-success.mr-3.p-2.border.border-success
                        = @question_votes
                        .small
                          votos
                      %h6.d-inline-block.text-secondary.ml-3
                        = question.answers.length
                        .small
                          respuestas
                  - else
                    %td.align-middle.text-center.pb-0
                      %h6.d-inline-block.text-secondary.mr-3
                        = @question_votes
                        .small
                          votos
                      %h6.d-inline-block.text-secondary.ml-3
                        = question.answers.length
                        .small
                          respuestas
                  %td.pb-0
                    %h5
                      =link_to truncate(question.title, length:60), question
                    .row
                      .col-7
                        - 0.upto(question.question_tags.size)  {|index|
                        -  if index>5
                          - break  
                        -  elsif(question.question_tags[index]!=nil)
                          %span.tagstyle.p-1.mr-1
                            =question.question_tags[index].tag.name
                        - }
                      .col-5.text-right
                        - if question.created_at > 1.day.ago
                          %p.small="Hace 1 dia por #{question.user.first_name} #{question.user.last_name}" 
                        - else   
                          %p.small= "Hace  #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
    .row
      .col-12
        = will_paginate @taggy, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
  -elsif params[:search] == nil
    .row.mt-3.justify-content-center
      .col-5.categorys
        %ul.nav.nav-tabs.border-bottom-0.mt-5{:role => "tablist"}
          %li.active.nav-item.w-50.text-center
            %a.nav-link.active.border-left-0{"data-toggle" => "tab", :href => "#home"} Populares
          %li.nav-item.w-50.text-center
            %a.nav-link{"data-toggle" => "tab", :href => "#menu1"} Recientes
      .col-4.text-right.mt-2
        = link_to new_question_path do
          %button.btn.btn-primary.mt-0.p-2.rounded-0{:type => "button"}
            Formular pregunta
    .row.justify-content-center
      .col-9
        .tab-content
          #home.tab-pane.fade.in.active.show            
            %table.table#popularquestions.bg-white
              %tbody
                - @questions.each do |question|
                  -@question_votes = Vote.where({votable_type: :Question, votable_id:question.id})
                  -@question_votes = @question_votes.select{|vote| vote.vote_flag}.size - @question_votes.select{|vote| !vote.vote_flag}.size
                  %tr.border-top-0
                    -if @question_votes  < 0
                      %td.align-middle.text-center.pb-0
                        %h6.d-inline-block.text-danger.mr-3.p-2.border.border-danger
                          = @question_votes
                          .small
                            votos
                        %h6.d-inline-block.text-secondary.ml-3
                          = question.answers.length
                          .small
                            respuestas
                    -elsif @question_votes  > 0
                      %td.align-middle.text-center.pb-0
                        %h6.d-inline-block.text-success.mr-3.p-2.border.border-success
                          = @question_votes
                          .small
                            votos
                        %h6.d-inline-block.text-secondary.ml-3
                          = question.answers.length
                          .small
                            respuestas
                    - else
                      %td.align-middle.text-center.pb-0
                        %h6.d-inline-block.text-secondary.mr-3
                          = @question_votes
                          .small
                            votos
                        %h6.d-inline-block.text-secondary.ml-3
                          = question.answers.length
                          .small
                            respuestas
                    %td.pb-0
                      %h5
                        =link_to truncate(question.title, length:60), question
                      .row
                        .col-7
                          - 0.upto(question.question_tags.size)  {|index|
                          -  if index>5
                            - break  
                          -  elsif(question.question_tags[index]!=nil)
                            %span.tagstyle.p-1.mr-1
                              =question.question_tags[index].tag.name
                          - }
                        .col-5.text-right
                          - if question.created_at > 1.day.ago
                            %p.small="Hace 1 dia por #{question.user.first_name} #{question.user.last_name}" 
                          - else   
                            %p.small= "Hace  #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
          
          #menu1.tab-pane.fade  
            %table.table#popularquestions.bg-white
              %tbody
                - @lastQuestions.each do |question|
                  -@question_votes = Vote.where({votable_type: :Question, votable_id:question.id})
                  -@question_votes = @question_votes.select{|vote| vote.vote_flag}.size - @question_votes.select{|vote| !vote.vote_flag}.size
                  %tr.border-top-0
                    -if @question_votes  < 0
                      %td.align-middle.text-center.pb-0
                        %h6.d-inline-block.text-danger.mr-3.p-2.border.border-danger
                          = @question_votes
                          .small
                            votos
                        %h6.d-inline-block.text-secondary.ml-3
                          = question.answers.length
                          .small
                            respuestas
                    -elsif @question_votes  > 0
                      %td.align-middle.text-center.pb-0
                        %h6.d-inline-block.text-success.mr-3.p-2.border.border-success
                          = @question_votes
                          .small
                            votos
                        %h6.d-inline-block.text-secondary.ml-3
                          = question.answers.length
                          .small
                            respuestas
                    - else
                      %td.align-middle.text-center.pb-0
                        %h6.d-inline-block.text-secondary.mr-3
                          = @question_votes
                          .small
                            votos
                        %h6.d-inline-block.text-secondary.ml-3
                          = question.answers.length
                          .small
                            respuestas
                    %td.pb-0
                      %h5
                        =link_to truncate(question.title, length:60), question
                      .row
                        .col-7
                          - 0.upto(question.question_tags.size)  {|index|
                          -  if index>5
                            - break  
                          -  elsif(question.question_tags[index]!=nil)
                            %span.tagstyle.p-1.mr-1
                              =question.question_tags[index].tag.name
                          - }
                        .col-5.text-right
                          - if question.created_at > 1.day.ago
                            %p.small="Hace 1 dia por #{question.user.first_name} #{question.user.last_name}" 
                          - else   
                            %p.small= "Hace  #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
          
  - elsif @findQuestions == []
    .row.mt-5
      .col-1
      .col-10.text-center
        .card.text-white#popular
          %h5.mt-1.font-weight-bold
            Resultados de la búsqueda
    .row.justify-content-center
      .col-10
        .card.imageContainer
          .row.justify-content-center
            .col-6.text-center
              %h5.font-weight-bold.mt-5
                No hubo resultados en la búsqueda
              %img.img-fluid(src="https://d30y9cdsu7xlg0.cloudfront.net/png/1635-200.png" alt="")
              %p
                También puede realizar búsquedas por etiquetas.
  - else
    .row.mt-3.justify-content-center
      .col-5.categorys
        %ul.nav.nav-tabs.border-bottom-0.mt-5{:role => "tablist"}
          %li.nav-item.w-100.text-center
            %a.nav-link.active.border-left-0.font-weight-bold{"data-toggle" => "tab", :href => "#home"} Resultados de la busqueda
      .col-4.text-right.mt-2
        = link_to new_question_path do
          %button.btn.btn-primary.mt-0.p-2.rounded-0{:type => "button"}
            Formular pregunta
    .row.justify-content-center
      .col-9
        %table.table#popularquestions.bg-white
          %tbody
            - @findQuestion.each do |question|
              -@question_votes = Vote.where({votable_type: :Question, votable_id:question.id})
              -@question_votes = @question_votes.select{|vote| vote.vote_flag}.size - @question_votes.select{|vote| !vote.vote_flag}.size
              %tr.border-top-0
                -if @question_votes  < 0
                  %td.align-middle.text-center.pb-0
                    %h6.d-inline-block.text-danger.mr-3.p-2.border.border-danger
                      = @question_votes
                      .small
                        votos
                    %h6.d-inline-block.text-secondary.ml-3
                      = question.answers.length
                      .small
                        respuestas
                -elsif @question_votes  > 0
                  %td.align-middle.text-center.pb-0
                    %h6.d-inline-block.text-success.mr-3.p-2.border.border-success
                      = @question_votes
                      .small
                        votos
                    %h6.d-inline-block.text-secondary.ml-3
                      = question.answers.length
                      .small
                        respuestas
                - else
                  %td.align-middle.text-center.pb-0
                    %h6.d-inline-block.text-secondary.mr-3
                      = @question_votes
                      .small
                        votos
                    %h6.d-inline-block.text-secondary.ml-3
                      = question.answers.length
                      .small
                        respuestas
                %td.pb-0
                  %h5
                    =link_to truncate(question.title, length:60), question
                  .row
                    .col-7
                      - 0.upto(question.question_tags.size)  {|index|
                      -  if index>5
                        - break  
                      -  elsif(question.question_tags[index]!=nil)
                        %span.tagstyle.p-1.mr-1
                          =question.question_tags[index].tag.name
                      - }
                    .col-5.text-right
                      - if question.created_at > 1.day.ago
                        %p.small="Hace 1 dia por #{question.user.first_name} #{question.user.last_name}" 
                      - else   
                        %p.small= "Hace  #{time_ago_in_words(question.created_at.utc.to_i)} por #{question.user.first_name} #{question.user.last_name}"
    .row
      .col-12
        = will_paginate @findQuestions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/questions/new.html.haml
.container
    .row
        .col-8
            .mt-4
                = render 'form'
        .col-4
            .mt-4
                #exampletitle
                    .card.p-4.colorexample
                        %h5
                            ¿Cómo preguntar?
                        %p
                            %strong
                            ¿Tu pregunta es sobre programación?
                        %p
                            Preferimos preguntas que pueden ser respondidas, no simplemente debatidas.
                        %p
                            Proporciona detalles. Comparte lo que ya sabes.
                #examplebody
                    .card.p-4.colorexample
                        %h5
                            ¿Cómo formatear?
                        %li.mt-2
                            Usa saltos de línea para separar párrafos
                        %li.mt-2
                            Para añadir un salto de línea, coloc 2 espacios al final
                        %li.mt-2
                            %i
                                _cursiva_
                            o
                            %strong
                                **negrita**
                        %li.mt-2
                            identa el código con 4 espacios
                        %li.mt-2
                            Las palabras reservadas del código cambian de color
                        %li 
                            Crea un bloque de cita poniendo > al conmienzo de la línea
                #exampletags
                    .card.p-4.colorexample
                        %h5
                            ¿Cómo etiquetar?
                        %p
                            Una etiqueta es una palabra clave que categoriza su pregunta con otras preguntas similares. Elija una o más etiquetas que ayudarán a los demas usuarios a encontrar e interpretar su pregunta.
                        %li
                            Completa la oración: mi pregunta es sobre...
                        %li
                            Use etiquetas que describan cosas o conceptos que son esenciales, no relacionados con su pregunta
                        %li
                            Lea la descripción que aparece debajo de "Etiquetas"
                        %li
                            Combine palabras múltiples en palabras sueltas con guiones (por ejemplo, android-studio)
                        %li
                            Crear nuevas etiquetas es un privilegio; Si su etiqueta no existe, asegurese que esté bien redactada y tenga sentido

-# = link_to 'Back', questions_path

app/views/questions/show.html.haml
.container
  .row.mt-5
    .col-8
      .max
        %h4.border-bottom.pb-3.mb-5.max
          = @question.title.capitalize
      .row.card.noblanco.pb-2
        .row.pt-3
          .col-1.text-right
            .row.pt-2
            = link_to(:controller => "questions", :action => "upvote", :id => @question) do
              = icon(@tu_class, 'thumbs-up', class:"text-success")
            
            .row.pt-2
            %h3.text-secondary
              = @question_votes
            .row.pt-0
            = link_to(:controller => "questions", :action => "downvote", :id => @question) do
              = icon(@td_class, 'thumbs-down',class:"text-danger")
            .row
            -if user_signed_in?
              -if current_user.id == @question.user.id
                = link_to edit_question_path(@question) do
                  = icon("far", "edit", class:"iconoedit")
              
          .col-9.max.mb-0
            = sanitize(@question.body).html_safe
          .col-11.text-right.mt-0
            .small
              = @question.user.first_name + " " + @question.user.last_name
      -if @answers.length>0
        %h4.pt-4.border-bottom.pb-3  
          = @answers.length
          - if  @answers.length>1
            Respuestas
          - else 
            Respuesta
        - @answers.each do |answer|
          .row.card.mt-3.noblanco.pb-2
            .row.pt-4
              .col-1.text-right
                .row.pt-2
                  -@vote = Vote.find_by({votable_type: "Answer",votable_id: answer.id,voter_id:current_user.id}) if(current_user)
                  -if(@vote)
                    -if(@vote.vote_flag)
                      -@td_class_answer = 'far'
                      -@tu_class_answer = 'fas'
                    -else 
                      -@td_class_answer = 'fas'
                      -@tu_class_answer = 'far'
                  -else
                    -@td_class_answer = 'far'
                    -@tu_class_answer = 'far'
                = link_to(:controller => "answers", :action => "upvote", :question_id => @question,:id => answer) do
                  = icon(@tu_class_answer, 'thumbs-up', class:"text-success")
                %h3.text-secondary
                  -@answer_votes= Vote.where({votable_type: :Answer, votable_id:answer.id})
                  = @answer_votes = @answer_votes.select{|vote| vote.vote_flag}.size - @answer_votes.select{|vote| !vote.vote_flag}.size
                .row.pt-0
                = link_to(:controller => "answers", :action => "downvote", :question_id => @question,:id => answer) do
                  = icon(@td_class_answer, 'thumbs-down', class:"text-danger")  
                -if user_signed_in?
                  -if @question.user_id == current_user.id && @question.answers.where(status:"accepted").empty?
                    .row
                    = link_to "#{@question.id}/answers/#{answer.id}",method: :put do
                      = icon("far","check-square")
                  -if @question.user_id == current_user.id && answer.status == "accepted"
                    .row
                    = link_to "#{@question.id}/answers/#{answer.id}",method: :put do
                      = icon("fas","check", class:"fa-1x text-success text-right")
                  - elsif answer.status == "accepted"
                    = icon("fas","check", class:"fa-1x text-success text-right")
                -elsif answer.status == "accepted"
                  = icon("fas","check", class:"fa-1x text-success text-right")
        
              .col-9.max
                = sanitize(answer.body).html_safe
              .col-11.text-right.small
                = answer.user.first_name + " " + answer.user.last_name
      %hr.mt-5          
      %h5.pt-4.border-bottom.pb-3 
        Tu Respuesta
        .row.pt-4
          .col-12
            = render 'formanswer'
  
    .col-4  
      .card.position-fixed.ml-4.colorexample.p-3.relacionadas
        %h5.mb-4.text-center Preguntas relacionadas
        - i = []
        - @relatedQuestions.each do |question|
          %h6
            .small.mb-2
              = link_to truncate(question.title, length:70), question_path(question)
              - i.push('newtag')
              -break if i.length > 8

            
         